# Generated by Django 3.1.7 on 2021-02-24 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(blank=True, max_length=30)),
                ('account_no', models.CharField(blank=True, max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=30)),
                ('amount_invested', models.CharField(max_length=30)),
                ('date_of_investment', models.DateField(blank=True, null=True, verbose_name='Date of Investment (mm/dd/yyyy)')),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email_address', models.CharField(max_length=30)),
                ('return_of_investment', models.CharField(max_length=30)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date (mm/dd/yyyy)')),
                ('users_name', models.CharField(max_length=30)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('duration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentic_fx.duration')),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investor_name', models.CharField(blank=True, max_length=30)),
                ('account_no', models.CharField(blank=True, max_length=30)),
                ('bank_name', models.CharField(blank=True, max_length=30)),
                ('amount_invested', models.CharField(max_length=30)),
                ('date_of_investment', models.DateField(blank=True, null=True, verbose_name='Date of Investment (mm/dd/yyyy)')),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email_address', models.CharField(max_length=30)),
                ('return_of_investment', models.CharField(max_length=30)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Due Date (mm/dd/yyyy)')),
                ('users_name', models.CharField(max_length=30)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('export_to_CSV', models.BooleanField(default=False)),
                ('duration', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentic_fx.duration')),
            ],
        ),
    ]
